### ISSUE TITLE
Jpeg Baseline Decoder

### ISSUE THREAD

**Issue by BrianMcRails** [ivmartel/dwv-react#5] opened 2018-04-06 23:58 UTC
Having some trouble figuring out how to get the jpeg baseline decoder to work. I brought the file in locally along with jpg.js, and added it as a decoder script like this:
```js
            dwv.image.decoderScripts = {
                "jpeg-baseline": "./decode-jpegbaseline.js"
            };
```
but at runtime when trying to load a jpeg baseline image i get the following error 8 times in my console.
Uncaught SyntaxError: Unexpected token <      decode-jpegbaseline.js:1 

It's definitely possible I am missing something small/obvious, but may be a bug with react integration. Do you have any insight in to this? If not i can dig deeper.

**Comment by BrianMcRails** [comment] 2018-04-08 06:56
even pointing to the node modules location still gives the same error. I found (this issue)[https://github.com/react-boilerplate/react-boilerplate/issues/1676] that seems like it has something to do with service workers and react router. I'll give fiddling with it and let you know if I get it sorted out.

**Comment by ivmartel** [comment] 2018-04-09 13:08
I get the same error... 

JPEG decoding uses the [web workers API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) (ie web multi threading, different from the [service worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) used for caching data) and I'm not sure how to include them in the code...

**Comment by ivmartel** [comment] 2018-04-11 21:43
Just committed a not so wonderful solution: I added the decoders to the public folder, that way they are not compiled by webpack and can be accessed as scripts. 

All the posts I see talk about ejecting and configuring webpack to either copy the files (as done in [dwv-vue:#6](https://github.com/ivmartel/dwv-vue/issues/6)) or use the webpack [worker-loader](https://github.com/webpack-contrib/worker-loader) which I do not see how to make it work...

Now the problem is adding the files to the service worker, which does not seem trivial...

**Closed** 2018-08-24 10:31 UTC
Labels: bug, question
